### ISSUE TITLE
[Improvement] Electricity Consumption as End Sensor

### ISSUE THREAD

**Issue by bzumik1** [bruxy70/Venetian-Blinds-Control#20]
Hello, I'm considering the use of a Sonoff device with electricity consumption monitoring capabilities. My intention is to utilize this feature for automatic calibration and as an endpoint indicator, particularly when the blind reaches its end position. I'm unsure if this aligns with your perspective and if it even would be usable. The cost difference between the version with power consumption measurement and the one without is approximately 1-2 dollars. I'd really appreciate your insights on whether this choice makes sense.

**Comment by bzumik1** [comment]
I was thinking about this onece again and it could look something like this

```yaml
cover:
  - platform: venetian_blinds
    id: my_venetian_blinds
    open_action:
      # Open action configuration
    close_action:
      # Close action configuration
    stop_action:
      # Stop action configuration
    open_duration: 10s
    close_duration: 10s
    tilt_duration: 2s
    actuator_activation_duration: 1s
    assumed_state: true
    calibration_cycles: 5
    open_sensor: sensor1
    close_sensor: sensor2
```

In this configuration, the blinds would move up and down 5 times, and the time for the up and down movement would be calculated as the average of these motions. However, I am uncertain if this approach will be sufficiently precise. If the consumption can be measured quickly and accurately, we could also consider adding calibration for the tilt, as the consumption during tilting will be lower than when the blinds are fully moving up. Another idea is to implement stuck detection. If the sensor detects a higher load than usual, the blinds could stop, similar to the safety feature in standing desks.
