### ISSUE TITLE
Cover schema deprecation fix breaks interoperability with MQTT component

### ISSUE THREAD

**Issue by Megu** [bruxy70/Venetian-Blinds-Control#26]
Post cover schema update code ceases to build:
```
INFO ESPHome 2025.6.0
INFO Reading configuration /config/esphome/nspanel0.yaml...
INFO Generating C++ source...
ERROR ID mqtt_mqttcovercomponent_id is already registered
```
I'd assume this relates to me being forced into MQTT for the sake of another component.
After reverting changes back to deprecated schema, the code runs just fine.

Config snippet:
```
mqtt:
  broker: !secret mqtt_ip
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false

cover:
  - platform: venetian_blinds
    name: Cover
    id: cover1
    device_class: shutter
    open_action:
      - switch.turn_on: relay_1
    open_duration: $cover_open_duration
    close_action:
      - switch.turn_on: relay_2
    close_duration: $cover_close_duration
    tilt_duration: $cover_tilt_duration
    stop_action:
      - switch.turn_off: relay_1
      - switch.turn_off: relay_2

```
